// Bilder, die die Prüfung noch nicht bestanden haben. Zum Veröffentlichen zurück in katalog.mjs (Thema staedte-deutschland bzw. staedte-welt) setzen.
// Übersetzungen stehen schon in i18n/*.mjs.
export default [
      { slug: "kaiserdom-speyer", titel: "Kaiserdom Speyer", alt: "Der romanische Dom mit vier Türmen und zwei Kuppeln, davor ein Park mit Bäumen", prompt: "Speyer Cathedral, a huge Romanesque cathedral of red sandstone in side view: at the left (west) end a large octagonal dome flanked by two slender square towers with pointed pyramid roofs, at the right (east) end a smaller octagonal dome flanked by two more slender square towers with pointed pyramid roofs, a long nave with rows of round-arched windows between them, a park with old trees and a giant round stone bowl in front, a lively street-level view with a few people and trees for scale, no signs or shop signs, no lettering or numbers anywhere, boats, ferries, trams and buses have plain sides without names or numbers, clock faces show only simple tick marks without numerals, water drawn with simple wave lines and no mirrored reflections, no flags with symbols, the complete landmark fully visible including its top, nothing cut off at the edges" },
      { slug: "tower-bridge-london", titel: "Tower Bridge London", alt: "Die Tower Bridge mit zwei Türmen über die Themse", prompt: "Tower Bridge in London seen straight from the side, perfectly symmetric: two identical tall gothic stone towers, each tower stands on its own big stone pier in the river Thames, the two towers are joined at the top by two straight horizontal high walkways, below them a flat straight road deck joins the towers at low height, from the outer side of each tower a hanging chain curves down to the river bank, nothing else on the water, a lively street-level view with a few people and trees for scale, no signs or shop signs, no lettering or numbers anywhere, boats, ferries, trams and buses have plain sides without names or numbers, clock faces show only simple tick marks without numerals, water drawn with simple wave lines and no mirrored reflections, no flags with symbols, the complete landmark fully visible including its top, nothing cut off at the edges" },
      { slug: "karlsbruecke-prag", titel: "Karlsbrücke Prag", alt: "Die Steinbrücke mit Figuren und Brückenturm, dahinter die Prager Burg", prompt: "the Charles Bridge in Prague: a long stone bridge with many arches over the Vltava river, dark baroque statues on the parapets, a gothic bridge tower at the near end, Prague Castle with the cathedral on the hill behind, people walking on the bridge, the river empty below, no signs, a lively street-level view with a few people and trees for scale, no signs or shop signs, no lettering or numbers anywhere, boats, ferries, trams and buses have plain sides without names or numbers, clock faces show only simple tick marks without numerals, water drawn with simple wave lines and no mirrored reflections, no flags with symbols, the complete landmark fully visible including its top, nothing cut off at the edges" },
      { slug: "freiheitsstatue-new-york", titel: "Freiheitsstatue New York", alt: "Die Freiheitsstatue mit Fackel auf ihrem Sockel auf einer kleinen Insel", prompt: "exactly one single Statue of Liberty: the tall statue of a woman with a crown and a raised torch in her right hand and a plain blank tablet in her left arm, one head, two arms, standing on a big plain stone pedestal on a small island with trees, calm water around, no boats, no signs, a lively street-level view with a few people and trees for scale, no signs or shop signs, no lettering or numbers anywhere, boats, ferries, trams and buses have plain sides without names or numbers, clock faces show only simple tick marks without numerals, water drawn with simple wave lines and no mirrored reflections, no flags with symbols, the complete landmark fully visible including its top, nothing cut off at the edges" },
      { slug: "tafelberg-kapstadt", titel: "Tafelberg Kapstadt", alt: "Der flache Tafelberg über Kapstadt, davor Hafen und Boote", prompt: "Table Mountain in Cape Town: a wide flat-topped mountain filling the upper half, the city with small houses and trees at its foot, a sandy beach with a few small rowing boats with plain hulls lying on the sand, no ships, no ferry, no signs, a lively street-level view with a few people and trees for scale, no signs or shop signs, no lettering or numbers anywhere, boats, ferries, trams and buses have plain sides without names or numbers, clock faces show only simple tick marks without numerals, water drawn with simple wave lines and no mirrored reflections, no flags with symbols, the complete landmark fully visible including its top, nothing cut off at the edges" },
];
